export const CHANGE_PRODUCT_NAME = 'CHANGE_PRODUCT_NAME';
export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const CHANGE_PRICE = 'CHANGE_PRICE';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CHANGE_ID = 'CHANGE_ID';

export default {
  CHANGE_PRODUCT_NAME,
  CHANGE_PRICE,
  SAVE_PRODUCT,
  EDIT_PRODUCT,
  DELETE_PRODUCT,
  CHANGE_ID
};
